name = "feedback-reporter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "feedback-db"
database_id = "89ac28ba-41ec-40db-bb46-35b19a168ff0"

[ai]
binding = "AI"

[triggers]
crons = ["0 9 * * *"]